// Code generated by go-swagger; DO NOT EDIT.

package testcase

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/testra/testra-cli/api/models"
)

// GetTestcasesReader is a Reader for the GetTestcases structure.
type GetTestcasesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTestcasesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetTestcasesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetTestcasesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetTestcasesOK creates a GetTestcasesOK with default headers values
func NewGetTestcasesOK() *GetTestcasesOK {
	return &GetTestcasesOK{}
}

/*GetTestcasesOK handles this case with default header values.

Successful Response
*/
type GetTestcasesOK struct {
	Payload []*models.Testcase
}

func (o *GetTestcasesOK) Error() string {
	return fmt.Sprintf("[GET /projects/{projectId}/testcases][%d] getTestcasesOK  %+v", 200, o.Payload)
}

func (o *GetTestcasesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTestcasesDefault creates a GetTestcasesDefault with default headers values
func NewGetTestcasesDefault(code int) *GetTestcasesDefault {
	return &GetTestcasesDefault{
		_statusCode: code,
	}
}

/*GetTestcasesDefault handles this case with default header values.

Any other errors
*/
type GetTestcasesDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the get testcases default response
func (o *GetTestcasesDefault) Code() int {
	return o._statusCode
}

func (o *GetTestcasesDefault) Error() string {
	return fmt.Sprintf("[GET /projects/{projectId}/testcases][%d] getTestcases default  %+v", o._statusCode, o.Payload)
}

func (o *GetTestcasesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
