// Code generated by go-swagger; DO NOT EDIT.

package testcase

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTestcaseParams creates a new GetTestcaseParams object
// with the default values initialized.
func NewGetTestcaseParams() *GetTestcaseParams {
	var ()
	return &GetTestcaseParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTestcaseParamsWithTimeout creates a new GetTestcaseParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTestcaseParamsWithTimeout(timeout time.Duration) *GetTestcaseParams {
	var ()
	return &GetTestcaseParams{

		timeout: timeout,
	}
}

// NewGetTestcaseParamsWithContext creates a new GetTestcaseParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTestcaseParamsWithContext(ctx context.Context) *GetTestcaseParams {
	var ()
	return &GetTestcaseParams{

		Context: ctx,
	}
}

// NewGetTestcaseParamsWithHTTPClient creates a new GetTestcaseParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTestcaseParamsWithHTTPClient(client *http.Client) *GetTestcaseParams {
	var ()
	return &GetTestcaseParams{
		HTTPClient: client,
	}
}

/*GetTestcaseParams contains all the parameters to send to the API endpoint
for the get testcase operation typically these are written to a http.Request
*/
type GetTestcaseParams struct {

	/*ID
	  Testcase Id

	*/
	ID string
	/*ProjectID
	  Project Id

	*/
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get testcase params
func (o *GetTestcaseParams) WithTimeout(timeout time.Duration) *GetTestcaseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get testcase params
func (o *GetTestcaseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get testcase params
func (o *GetTestcaseParams) WithContext(ctx context.Context) *GetTestcaseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get testcase params
func (o *GetTestcaseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get testcase params
func (o *GetTestcaseParams) WithHTTPClient(client *http.Client) *GetTestcaseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get testcase params
func (o *GetTestcaseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get testcase params
func (o *GetTestcaseParams) WithID(id string) *GetTestcaseParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get testcase params
func (o *GetTestcaseParams) SetID(id string) {
	o.ID = id
}

// WithProjectID adds the projectID to the get testcase params
func (o *GetTestcaseParams) WithProjectID(projectID string) *GetTestcaseParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the get testcase params
func (o *GetTestcaseParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *GetTestcaseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
