// Code generated by go-swagger; DO NOT EDIT.

package testcase

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/testra/testra-cli/api/models"
)

// UpdateTestcaseReader is a Reader for the UpdateTestcase structure.
type UpdateTestcaseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateTestcaseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdateTestcaseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewUpdateTestcaseNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewUpdateTestcaseDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateTestcaseOK creates a UpdateTestcaseOK with default headers values
func NewUpdateTestcaseOK() *UpdateTestcaseOK {
	return &UpdateTestcaseOK{}
}

/*UpdateTestcaseOK handles this case with default header values.

Successful update of given Testcase
*/
type UpdateTestcaseOK struct {
	Payload *models.Testcase
}

func (o *UpdateTestcaseOK) Error() string {
	return fmt.Sprintf("[PUT /projects/{projectId}/testcases/{id}][%d] updateTestcaseOK  %+v", 200, o.Payload)
}

func (o *UpdateTestcaseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Testcase)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateTestcaseNotFound creates a UpdateTestcaseNotFound with default headers values
func NewUpdateTestcaseNotFound() *UpdateTestcaseNotFound {
	return &UpdateTestcaseNotFound{}
}

/*UpdateTestcaseNotFound handles this case with default header values.

Testcase not found
*/
type UpdateTestcaseNotFound struct {
	Payload *models.ErrorResponse
}

func (o *UpdateTestcaseNotFound) Error() string {
	return fmt.Sprintf("[PUT /projects/{projectId}/testcases/{id}][%d] updateTestcaseNotFound  %+v", 404, o.Payload)
}

func (o *UpdateTestcaseNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateTestcaseDefault creates a UpdateTestcaseDefault with default headers values
func NewUpdateTestcaseDefault(code int) *UpdateTestcaseDefault {
	return &UpdateTestcaseDefault{
		_statusCode: code,
	}
}

/*UpdateTestcaseDefault handles this case with default header values.

Any other errors
*/
type UpdateTestcaseDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the update testcase default response
func (o *UpdateTestcaseDefault) Code() int {
	return o._statusCode
}

func (o *UpdateTestcaseDefault) Error() string {
	return fmt.Sprintf("[PUT /projects/{projectId}/testcases/{id}][%d] updateTestcase default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateTestcaseDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
