// Code generated by go-swagger; DO NOT EDIT.

package testcase

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/testra/testra-cli/api/models"
)

// NewUpdateTestcaseParams creates a new UpdateTestcaseParams object
// with the default values initialized.
func NewUpdateTestcaseParams() *UpdateTestcaseParams {
	var ()
	return &UpdateTestcaseParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateTestcaseParamsWithTimeout creates a new UpdateTestcaseParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateTestcaseParamsWithTimeout(timeout time.Duration) *UpdateTestcaseParams {
	var ()
	return &UpdateTestcaseParams{

		timeout: timeout,
	}
}

// NewUpdateTestcaseParamsWithContext creates a new UpdateTestcaseParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateTestcaseParamsWithContext(ctx context.Context) *UpdateTestcaseParams {
	var ()
	return &UpdateTestcaseParams{

		Context: ctx,
	}
}

// NewUpdateTestcaseParamsWithHTTPClient creates a new UpdateTestcaseParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateTestcaseParamsWithHTTPClient(client *http.Client) *UpdateTestcaseParams {
	var ()
	return &UpdateTestcaseParams{
		HTTPClient: client,
	}
}

/*UpdateTestcaseParams contains all the parameters to send to the API endpoint
for the update testcase operation typically these are written to a http.Request
*/
type UpdateTestcaseParams struct {

	/*Body*/
	Body *models.TestcaseRequest
	/*ID
	  Testcase Id

	*/
	ID string
	/*ProjectID
	  Project Id

	*/
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update testcase params
func (o *UpdateTestcaseParams) WithTimeout(timeout time.Duration) *UpdateTestcaseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update testcase params
func (o *UpdateTestcaseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update testcase params
func (o *UpdateTestcaseParams) WithContext(ctx context.Context) *UpdateTestcaseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update testcase params
func (o *UpdateTestcaseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update testcase params
func (o *UpdateTestcaseParams) WithHTTPClient(client *http.Client) *UpdateTestcaseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update testcase params
func (o *UpdateTestcaseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update testcase params
func (o *UpdateTestcaseParams) WithBody(body *models.TestcaseRequest) *UpdateTestcaseParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update testcase params
func (o *UpdateTestcaseParams) SetBody(body *models.TestcaseRequest) {
	o.Body = body
}

// WithID adds the id to the update testcase params
func (o *UpdateTestcaseParams) WithID(id string) *UpdateTestcaseParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update testcase params
func (o *UpdateTestcaseParams) SetID(id string) {
	o.ID = id
}

// WithProjectID adds the projectID to the update testcase params
func (o *UpdateTestcaseParams) WithProjectID(projectID string) *UpdateTestcaseParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the update testcase params
func (o *UpdateTestcaseParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateTestcaseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
