// Code generated by go-swagger; DO NOT EDIT.

package counter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new counter API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for counter API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetCounters counters

Returns counters for Projects, Test executions, Test scenarions, Test cases and Test results

*/
func (a *Client) GetCounters(params *GetCountersParams) (*GetCountersOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetCountersParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getCounters",
		Method:             "GET",
		PathPattern:        "/counters",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetCountersReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetCountersOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
