// Code generated by go-swagger; DO NOT EDIT.

package counter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCountersParams creates a new GetCountersParams object
// with the default values initialized.
func NewGetCountersParams() *GetCountersParams {

	return &GetCountersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCountersParamsWithTimeout creates a new GetCountersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCountersParamsWithTimeout(timeout time.Duration) *GetCountersParams {

	return &GetCountersParams{

		timeout: timeout,
	}
}

// NewGetCountersParamsWithContext creates a new GetCountersParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCountersParamsWithContext(ctx context.Context) *GetCountersParams {

	return &GetCountersParams{

		Context: ctx,
	}
}

// NewGetCountersParamsWithHTTPClient creates a new GetCountersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCountersParamsWithHTTPClient(client *http.Client) *GetCountersParams {

	return &GetCountersParams{
		HTTPClient: client,
	}
}

/*GetCountersParams contains all the parameters to send to the API endpoint
for the get counters operation typically these are written to a http.Request
*/
type GetCountersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get counters params
func (o *GetCountersParams) WithTimeout(timeout time.Duration) *GetCountersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get counters params
func (o *GetCountersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get counters params
func (o *GetCountersParams) WithContext(ctx context.Context) *GetCountersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get counters params
func (o *GetCountersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get counters params
func (o *GetCountersParams) WithHTTPClient(client *http.Client) *GetCountersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get counters params
func (o *GetCountersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCountersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
