project_name: testra

builds:
- goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
  - "386"
  goarm:
  - "6"
  targets:
  - windows_amd64
  - windows_386
  - darwin_amd64
  - darwin_386
  - linux_amd64
  - linux_386
  main: .
  ldflags:
  - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: testra
  lang: go

archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

git:
  short_hash: true

brew:
  github:
    owner: testra
    name: homebrew-tap
  commit_author:
    name: testra
    email: testra.oss@gmail.com
  folder: Formula
  homepage: "https://github.com/testra/testra-cli"
  description: "CLI tool for Testra"
  skip_upload: false