language: go

#addons:
#  apt:
#    packages:
#    # needed for the nfpm pipe:
#    - rpm
#    # needed for the snap pipe:
#    - snapd

env:
# needed for the snap pipe:
- PATH=/snap/bin:$PATH GITHUB_TOKEN=$GITHUB_TOKEN

after_success:
- test -n "$TRAVIS_TAG"

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script:
    - curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux