// Code generated by go-swagger; DO NOT EDIT.

package scenario

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/testra/testra-cli/api/models"
)

// NewCreateScenarioParams creates a new CreateScenarioParams object
// with the default values initialized.
func NewCreateScenarioParams() *CreateScenarioParams {
	var ()
	return &CreateScenarioParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateScenarioParamsWithTimeout creates a new CreateScenarioParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateScenarioParamsWithTimeout(timeout time.Duration) *CreateScenarioParams {
	var ()
	return &CreateScenarioParams{

		timeout: timeout,
	}
}

// NewCreateScenarioParamsWithContext creates a new CreateScenarioParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateScenarioParamsWithContext(ctx context.Context) *CreateScenarioParams {
	var ()
	return &CreateScenarioParams{

		Context: ctx,
	}
}

// NewCreateScenarioParamsWithHTTPClient creates a new CreateScenarioParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateScenarioParamsWithHTTPClient(client *http.Client) *CreateScenarioParams {
	var ()
	return &CreateScenarioParams{
		HTTPClient: client,
	}
}

/*CreateScenarioParams contains all the parameters to send to the API endpoint
for the create scenario operation typically these are written to a http.Request
*/
type CreateScenarioParams struct {

	/*Body*/
	Body *models.ScenarioRequest
	/*ProjectID
	  Scenario Id

	*/
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create scenario params
func (o *CreateScenarioParams) WithTimeout(timeout time.Duration) *CreateScenarioParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create scenario params
func (o *CreateScenarioParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create scenario params
func (o *CreateScenarioParams) WithContext(ctx context.Context) *CreateScenarioParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create scenario params
func (o *CreateScenarioParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create scenario params
func (o *CreateScenarioParams) WithHTTPClient(client *http.Client) *CreateScenarioParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create scenario params
func (o *CreateScenarioParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create scenario params
func (o *CreateScenarioParams) WithBody(body *models.ScenarioRequest) *CreateScenarioParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create scenario params
func (o *CreateScenarioParams) SetBody(body *models.ScenarioRequest) {
	o.Body = body
}

// WithProjectID adds the projectID to the create scenario params
func (o *CreateScenarioParams) WithProjectID(projectID string) *CreateScenarioParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the create scenario params
func (o *CreateScenarioParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateScenarioParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
