// Code generated by go-swagger; DO NOT EDIT.

package test_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/testra/testra-cli/api/models"
)

// GetTestGroupsReader is a Reader for the GetTestGroups structure.
type GetTestGroupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTestGroupsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetTestGroupsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetTestGroupsOK creates a GetTestGroupsOK with default headers values
func NewGetTestGroupsOK() *GetTestGroupsOK {
	return &GetTestGroupsOK{}
}

/*GetTestGroupsOK handles this case with default header values.

Successful Response
*/
type GetTestGroupsOK struct {
	Payload []*models.TestGroup
}

func (o *GetTestGroupsOK) Error() string {
	return fmt.Sprintf("[GET /projects/{projectId}/test-groups][%d] getTestGroupsOK  %+v", 200, o.Payload)
}

func (o *GetTestGroupsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
