// Code generated by go-swagger; DO NOT EDIT.

package test_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTestGroupsParams creates a new GetTestGroupsParams object
// with the default values initialized.
func NewGetTestGroupsParams() *GetTestGroupsParams {
	var ()
	return &GetTestGroupsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTestGroupsParamsWithTimeout creates a new GetTestGroupsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTestGroupsParamsWithTimeout(timeout time.Duration) *GetTestGroupsParams {
	var ()
	return &GetTestGroupsParams{

		timeout: timeout,
	}
}

// NewGetTestGroupsParamsWithContext creates a new GetTestGroupsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTestGroupsParamsWithContext(ctx context.Context) *GetTestGroupsParams {
	var ()
	return &GetTestGroupsParams{

		Context: ctx,
	}
}

// NewGetTestGroupsParamsWithHTTPClient creates a new GetTestGroupsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTestGroupsParamsWithHTTPClient(client *http.Client) *GetTestGroupsParams {
	var ()
	return &GetTestGroupsParams{
		HTTPClient: client,
	}
}

/*GetTestGroupsParams contains all the parameters to send to the API endpoint
for the get test groups operation typically these are written to a http.Request
*/
type GetTestGroupsParams struct {

	/*ProjectID
	  Project Id

	*/
	ProjectID string
	/*Type
	  Filter results by group type. Group type can be either FEATURE or NAMESPACE

	*/
	Type *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get test groups params
func (o *GetTestGroupsParams) WithTimeout(timeout time.Duration) *GetTestGroupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get test groups params
func (o *GetTestGroupsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get test groups params
func (o *GetTestGroupsParams) WithContext(ctx context.Context) *GetTestGroupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get test groups params
func (o *GetTestGroupsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get test groups params
func (o *GetTestGroupsParams) WithHTTPClient(client *http.Client) *GetTestGroupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get test groups params
func (o *GetTestGroupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProjectID adds the projectID to the get test groups params
func (o *GetTestGroupsParams) WithProjectID(projectID string) *GetTestGroupsParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the get test groups params
func (o *GetTestGroupsParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WithType adds the typeVar to the get test groups params
func (o *GetTestGroupsParams) WithType(typeVar *string) *GetTestGroupsParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the get test groups params
func (o *GetTestGroupsParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *GetTestGroupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if o.Type != nil {

		// query param type
		var qrType string
		if o.Type != nil {
			qrType = *o.Type
		}
		qType := qrType
		if qType != "" {
			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
