// Code generated by go-swagger; DO NOT EDIT.

package test_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/testra-tech/testra-cli/api/models"
)

// GetTestGroupsInExecutionReader is a Reader for the GetTestGroupsInExecution structure.
type GetTestGroupsInExecutionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTestGroupsInExecutionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetTestGroupsInExecutionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetTestGroupsInExecutionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetTestGroupsInExecutionOK creates a GetTestGroupsInExecutionOK with default headers values
func NewGetTestGroupsInExecutionOK() *GetTestGroupsInExecutionOK {
	return &GetTestGroupsInExecutionOK{}
}

/*GetTestGroupsInExecutionOK handles this case with default header values.

Successful Response
*/
type GetTestGroupsInExecutionOK struct {
	Payload []*models.TestGroup
}

func (o *GetTestGroupsInExecutionOK) Error() string {
	return fmt.Sprintf("[GET /projects/{projectId}/executions/{executionId}/groups][%d] getTestGroupsInExecutionOK  %+v", 200, o.Payload)
}

func (o *GetTestGroupsInExecutionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTestGroupsInExecutionDefault creates a GetTestGroupsInExecutionDefault with default headers values
func NewGetTestGroupsInExecutionDefault(code int) *GetTestGroupsInExecutionDefault {
	return &GetTestGroupsInExecutionDefault{
		_statusCode: code,
	}
}

/*GetTestGroupsInExecutionDefault handles this case with default header values.

Any other errors
*/
type GetTestGroupsInExecutionDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the get test groups in execution default response
func (o *GetTestGroupsInExecutionDefault) Code() int {
	return o._statusCode
}

func (o *GetTestGroupsInExecutionDefault) Error() string {
	return fmt.Sprintf("[GET /projects/{projectId}/executions/{executionId}/groups][%d] getTestGroupsInExecution default  %+v", o._statusCode, o.Payload)
}

func (o *GetTestGroupsInExecutionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
