// Code generated by go-swagger; DO NOT EDIT.

package test_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new test group API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for test group API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetTestGroups lists all test groups

Returns list of all test groups within given project

*/
func (a *Client) GetTestGroups(params *GetTestGroupsParams) (*GetTestGroupsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetTestGroupsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getTestGroups",
		Method:             "GET",
		PathPattern:        "/projects/{projectId}/test-groups",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetTestGroupsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetTestGroupsOK), nil

}

/*
GetTestGroupsInExecution lists all test groups under execution

Returns list of all test groups (features or namespaces) within given project and execution

*/
func (a *Client) GetTestGroupsInExecution(params *GetTestGroupsInExecutionParams) (*GetTestGroupsInExecutionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetTestGroupsInExecutionParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getTestGroupsInExecution",
		Method:             "GET",
		PathPattern:        "/projects/{projectId}/executions/{executionId}/groups",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetTestGroupsInExecutionReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetTestGroupsInExecutionOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
