// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/testra/testra-cli/api/models"
)

// TopProjectsReader is a Reader for the TopProjects structure.
type TopProjectsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TopProjectsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewTopProjectsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTopProjectsOK creates a TopProjectsOK with default headers values
func NewTopProjectsOK() *TopProjectsOK {
	return &TopProjectsOK{}
}

/*TopProjectsOK handles this case with default header values.

Successful Response
*/
type TopProjectsOK struct {
	Payload []*models.ProjectExecutionCounter
}

func (o *TopProjectsOK) Error() string {
	return fmt.Sprintf("[GET /projects/top][%d] topProjectsOK  %+v", 200, o.Payload)
}

func (o *TopProjectsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
