// Code generated by go-swagger; DO NOT EDIT.

package simulation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/testra/testra-cli/api/models"
)

// NewCreateSimulationParams creates a new CreateSimulationParams object
// with the default values initialized.
func NewCreateSimulationParams() *CreateSimulationParams {
	var ()
	return &CreateSimulationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateSimulationParamsWithTimeout creates a new CreateSimulationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateSimulationParamsWithTimeout(timeout time.Duration) *CreateSimulationParams {
	var ()
	return &CreateSimulationParams{

		timeout: timeout,
	}
}

// NewCreateSimulationParamsWithContext creates a new CreateSimulationParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateSimulationParamsWithContext(ctx context.Context) *CreateSimulationParams {
	var ()
	return &CreateSimulationParams{

		Context: ctx,
	}
}

// NewCreateSimulationParamsWithHTTPClient creates a new CreateSimulationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateSimulationParamsWithHTTPClient(client *http.Client) *CreateSimulationParams {
	var ()
	return &CreateSimulationParams{
		HTTPClient: client,
	}
}

/*CreateSimulationParams contains all the parameters to send to the API endpoint
for the create simulation operation typically these are written to a http.Request
*/
type CreateSimulationParams struct {

	/*Body*/
	Body *models.SimulationRequest
	/*ExecutionID
	  Execution Id

	*/
	ExecutionID string
	/*ProjectID
	  Result Id

	*/
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create simulation params
func (o *CreateSimulationParams) WithTimeout(timeout time.Duration) *CreateSimulationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create simulation params
func (o *CreateSimulationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create simulation params
func (o *CreateSimulationParams) WithContext(ctx context.Context) *CreateSimulationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create simulation params
func (o *CreateSimulationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create simulation params
func (o *CreateSimulationParams) WithHTTPClient(client *http.Client) *CreateSimulationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create simulation params
func (o *CreateSimulationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create simulation params
func (o *CreateSimulationParams) WithBody(body *models.SimulationRequest) *CreateSimulationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create simulation params
func (o *CreateSimulationParams) SetBody(body *models.SimulationRequest) {
	o.Body = body
}

// WithExecutionID adds the executionID to the create simulation params
func (o *CreateSimulationParams) WithExecutionID(executionID string) *CreateSimulationParams {
	o.SetExecutionID(executionID)
	return o
}

// SetExecutionID adds the executionId to the create simulation params
func (o *CreateSimulationParams) SetExecutionID(executionID string) {
	o.ExecutionID = executionID
}

// WithProjectID adds the projectID to the create simulation params
func (o *CreateSimulationParams) WithProjectID(projectID string) *CreateSimulationParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the create simulation params
func (o *CreateSimulationParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateSimulationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param executionId
	if err := r.SetPathParam("executionId", o.ExecutionID); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
