// Code generated by go-swagger; DO NOT EDIT.

package simulation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/testra/testra-cli/api/models"
)

// CreateSimulationReader is a Reader for the CreateSimulation structure.
type CreateSimulationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateSimulationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreateSimulationCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewCreateSimulationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateSimulationCreated creates a CreateSimulationCreated with default headers values
func NewCreateSimulationCreated() *CreateSimulationCreated {
	return &CreateSimulationCreated{}
}

/*CreateSimulationCreated handles this case with default header values.

Successful creation of Simulation
*/
type CreateSimulationCreated struct {
	Payload *models.Simulation
}

func (o *CreateSimulationCreated) Error() string {
	return fmt.Sprintf("[POST /projects/{projectId}/executions/{executionId}/simulations][%d] createSimulationCreated  %+v", 201, o.Payload)
}

func (o *CreateSimulationCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Simulation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSimulationDefault creates a CreateSimulationDefault with default headers values
func NewCreateSimulationDefault(code int) *CreateSimulationDefault {
	return &CreateSimulationDefault{
		_statusCode: code,
	}
}

/*CreateSimulationDefault handles this case with default header values.

Any other errors
*/
type CreateSimulationDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the create simulation default response
func (o *CreateSimulationDefault) Code() int {
	return o._statusCode
}

func (o *CreateSimulationDefault) Error() string {
	return fmt.Sprintf("[POST /projects/{projectId}/executions/{executionId}/simulations][%d] createSimulation default  %+v", o._statusCode, o.Payload)
}

func (o *CreateSimulationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
