// Code generated by go-swagger; DO NOT EDIT.

package simulation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSimulationsParams creates a new GetSimulationsParams object
// with the default values initialized.
func NewGetSimulationsParams() *GetSimulationsParams {
	var ()
	return &GetSimulationsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSimulationsParamsWithTimeout creates a new GetSimulationsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSimulationsParamsWithTimeout(timeout time.Duration) *GetSimulationsParams {
	var ()
	return &GetSimulationsParams{

		timeout: timeout,
	}
}

// NewGetSimulationsParamsWithContext creates a new GetSimulationsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSimulationsParamsWithContext(ctx context.Context) *GetSimulationsParams {
	var ()
	return &GetSimulationsParams{

		Context: ctx,
	}
}

// NewGetSimulationsParamsWithHTTPClient creates a new GetSimulationsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSimulationsParamsWithHTTPClient(client *http.Client) *GetSimulationsParams {
	var ()
	return &GetSimulationsParams{
		HTTPClient: client,
	}
}

/*GetSimulationsParams contains all the parameters to send to the API endpoint
for the get simulations operation typically these are written to a http.Request
*/
type GetSimulationsParams struct {

	/*ExecutionID
	  Execution Id

	*/
	ExecutionID string
	/*ProjectID
	  Project Id

	*/
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get simulations params
func (o *GetSimulationsParams) WithTimeout(timeout time.Duration) *GetSimulationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get simulations params
func (o *GetSimulationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get simulations params
func (o *GetSimulationsParams) WithContext(ctx context.Context) *GetSimulationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get simulations params
func (o *GetSimulationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get simulations params
func (o *GetSimulationsParams) WithHTTPClient(client *http.Client) *GetSimulationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get simulations params
func (o *GetSimulationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExecutionID adds the executionID to the get simulations params
func (o *GetSimulationsParams) WithExecutionID(executionID string) *GetSimulationsParams {
	o.SetExecutionID(executionID)
	return o
}

// SetExecutionID adds the executionId to the get simulations params
func (o *GetSimulationsParams) SetExecutionID(executionID string) {
	o.ExecutionID = executionID
}

// WithProjectID adds the projectID to the get simulations params
func (o *GetSimulationsParams) WithProjectID(projectID string) *GetSimulationsParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the get simulations params
func (o *GetSimulationsParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *GetSimulationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param executionId
	if err := r.SetPathParam("executionId", o.ExecutionID); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
