// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Counter Counter
// swagger:model Counter
type Counter struct {

	// projects count
	// Required: true
	ProjectsCount *int64 `json:"projectsCount"`

	// test cases count
	// Required: true
	TestCasesCount *int64 `json:"testCasesCount"`

	// test executions count
	// Required: true
	TestExecutionsCount *int64 `json:"testExecutionsCount"`

	// test results count
	// Required: true
	TestResultsCount *int64 `json:"testResultsCount"`

	// test scenarios count
	// Required: true
	TestScenariosCount *int64 `json:"testScenariosCount"`
}

// Validate validates this counter
func (m *Counter) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProjectsCount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTestCasesCount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTestExecutionsCount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTestResultsCount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTestScenariosCount(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Counter) validateProjectsCount(formats strfmt.Registry) error {

	if err := validate.Required("projectsCount", "body", m.ProjectsCount); err != nil {
		return err
	}

	return nil
}

func (m *Counter) validateTestCasesCount(formats strfmt.Registry) error {

	if err := validate.Required("testCasesCount", "body", m.TestCasesCount); err != nil {
		return err
	}

	return nil
}

func (m *Counter) validateTestExecutionsCount(formats strfmt.Registry) error {

	if err := validate.Required("testExecutionsCount", "body", m.TestExecutionsCount); err != nil {
		return err
	}

	return nil
}

func (m *Counter) validateTestResultsCount(formats strfmt.Registry) error {

	if err := validate.Required("testResultsCount", "body", m.TestResultsCount); err != nil {
		return err
	}

	return nil
}

func (m *Counter) validateTestScenariosCount(formats strfmt.Registry) error {

	if err := validate.Required("testScenariosCount", "body", m.TestScenariosCount); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Counter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Counter) UnmarshalBinary(b []byte) error {
	var res Counter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
