// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ProjectExecutionCounter ProjectExecutionCounter
// swagger:model ProjectExecutionCounter
type ProjectExecutionCounter struct {

	// no of executions
	// Required: true
	NoOfExecutions *int64 `json:"noOfExecutions"`

	// project name
	// Required: true
	ProjectName *string `json:"projectName"`
}

// Validate validates this project execution counter
func (m *ProjectExecutionCounter) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNoOfExecutions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProjectName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProjectExecutionCounter) validateNoOfExecutions(formats strfmt.Registry) error {

	if err := validate.Required("noOfExecutions", "body", m.NoOfExecutions); err != nil {
		return err
	}

	return nil
}

func (m *ProjectExecutionCounter) validateProjectName(formats strfmt.Registry) error {

	if err := validate.Required("projectName", "body", m.ProjectName); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProjectExecutionCounter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProjectExecutionCounter) UnmarshalBinary(b []byte) error {
	var res ProjectExecutionCounter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
