// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TestExecutionStats TestExecutionStats
// swagger:model TestExecutionStats
type TestExecutionStats struct {

	// execution Id
	ExecutionID string `json:"executionId,omitempty"`

	// expected failures
	ExpectedFailures int64 `json:"expectedFailures,omitempty"`

	// failed
	Failed int64 `json:"failed,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// others
	Others int64 `json:"others,omitempty"`

	// passed
	Passed int64 `json:"passed,omitempty"`

	// project Id
	ProjectID string `json:"projectId,omitempty"`
}

// Validate validates this test execution stats
func (m *TestExecutionStats) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TestExecutionStats) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TestExecutionStats) UnmarshalBinary(b []byte) error {
	var res TestExecutionStats
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
