// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TestStep TestStep
// swagger:model TestStep
type TestStep struct {

	// data table rows
	DataTableRows []*DataTableRow `json:"dataTableRows"`

	// index
	// Required: true
	Index *int64 `json:"index"`

	// text
	// Required: true
	Text *string `json:"text"`
}

// Validate validates this test step
func (m *TestStep) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDataTableRows(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIndex(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateText(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TestStep) validateDataTableRows(formats strfmt.Registry) error {

	if swag.IsZero(m.DataTableRows) { // not required
		return nil
	}

	for i := 0; i < len(m.DataTableRows); i++ {
		if swag.IsZero(m.DataTableRows[i]) { // not required
			continue
		}

		if m.DataTableRows[i] != nil {
			if err := m.DataTableRows[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("dataTableRows" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *TestStep) validateIndex(formats strfmt.Registry) error {

	if err := validate.Required("index", "body", m.Index); err != nil {
		return err
	}

	return nil
}

func (m *TestStep) validateText(formats strfmt.Registry) error {

	if err := validate.Required("text", "body", m.Text); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TestStep) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TestStep) UnmarshalBinary(b []byte) error {
	var res TestStep
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
