// Code generated by go-swagger; DO NOT EDIT.

package execution

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/testra/testra-cli/api/models"
)

// CreateExecutionReader is a Reader for the CreateExecution structure.
type CreateExecutionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateExecutionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreateExecutionCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewCreateExecutionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateExecutionCreated creates a CreateExecutionCreated with default headers values
func NewCreateExecutionCreated() *CreateExecutionCreated {
	return &CreateExecutionCreated{}
}

/*CreateExecutionCreated handles this case with default header values.

Successful creation of Execution
*/
type CreateExecutionCreated struct {
	Payload *models.Execution
}

func (o *CreateExecutionCreated) Error() string {
	return fmt.Sprintf("[POST /projects/{projectId}/executions][%d] createExecutionCreated  %+v", 201, o.Payload)
}

func (o *CreateExecutionCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Execution)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateExecutionDefault creates a CreateExecutionDefault with default headers values
func NewCreateExecutionDefault(code int) *CreateExecutionDefault {
	return &CreateExecutionDefault{
		_statusCode: code,
	}
}

/*CreateExecutionDefault handles this case with default header values.

Any other errors
*/
type CreateExecutionDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the create execution default response
func (o *CreateExecutionDefault) Code() int {
	return o._statusCode
}

func (o *CreateExecutionDefault) Error() string {
	return fmt.Sprintf("[POST /projects/{projectId}/executions][%d] createExecution default  %+v", o._statusCode, o.Payload)
}

func (o *CreateExecutionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
