// Code generated by go-swagger; DO NOT EDIT.

package execution

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetExecutionParams creates a new GetExecutionParams object
// with the default values initialized.
func NewGetExecutionParams() *GetExecutionParams {
	var ()
	return &GetExecutionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetExecutionParamsWithTimeout creates a new GetExecutionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetExecutionParamsWithTimeout(timeout time.Duration) *GetExecutionParams {
	var ()
	return &GetExecutionParams{

		timeout: timeout,
	}
}

// NewGetExecutionParamsWithContext creates a new GetExecutionParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetExecutionParamsWithContext(ctx context.Context) *GetExecutionParams {
	var ()
	return &GetExecutionParams{

		Context: ctx,
	}
}

// NewGetExecutionParamsWithHTTPClient creates a new GetExecutionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetExecutionParamsWithHTTPClient(client *http.Client) *GetExecutionParams {
	var ()
	return &GetExecutionParams{
		HTTPClient: client,
	}
}

/*GetExecutionParams contains all the parameters to send to the API endpoint
for the get execution operation typically these are written to a http.Request
*/
type GetExecutionParams struct {

	/*ID
	  Execution Id

	*/
	ID string
	/*ProjectID
	  Project Id

	*/
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get execution params
func (o *GetExecutionParams) WithTimeout(timeout time.Duration) *GetExecutionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get execution params
func (o *GetExecutionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get execution params
func (o *GetExecutionParams) WithContext(ctx context.Context) *GetExecutionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get execution params
func (o *GetExecutionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get execution params
func (o *GetExecutionParams) WithHTTPClient(client *http.Client) *GetExecutionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get execution params
func (o *GetExecutionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get execution params
func (o *GetExecutionParams) WithID(id string) *GetExecutionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get execution params
func (o *GetExecutionParams) SetID(id string) {
	o.ID = id
}

// WithProjectID adds the projectID to the get execution params
func (o *GetExecutionParams) WithProjectID(projectID string) *GetExecutionParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the get execution params
func (o *GetExecutionParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *GetExecutionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
