// Code generated by go-swagger; DO NOT EDIT.

package execution

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetExecutionsParams creates a new GetExecutionsParams object
// with the default values initialized.
func NewGetExecutionsParams() *GetExecutionsParams {
	var ()
	return &GetExecutionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetExecutionsParamsWithTimeout creates a new GetExecutionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetExecutionsParamsWithTimeout(timeout time.Duration) *GetExecutionsParams {
	var ()
	return &GetExecutionsParams{

		timeout: timeout,
	}
}

// NewGetExecutionsParamsWithContext creates a new GetExecutionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetExecutionsParamsWithContext(ctx context.Context) *GetExecutionsParams {
	var ()
	return &GetExecutionsParams{

		Context: ctx,
	}
}

// NewGetExecutionsParamsWithHTTPClient creates a new GetExecutionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetExecutionsParamsWithHTTPClient(client *http.Client) *GetExecutionsParams {
	var ()
	return &GetExecutionsParams{
		HTTPClient: client,
	}
}

/*GetExecutionsParams contains all the parameters to send to the API endpoint
for the get executions operation typically these are written to a http.Request
*/
type GetExecutionsParams struct {

	/*ProjectID
	  Project Id

	*/
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get executions params
func (o *GetExecutionsParams) WithTimeout(timeout time.Duration) *GetExecutionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get executions params
func (o *GetExecutionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get executions params
func (o *GetExecutionsParams) WithContext(ctx context.Context) *GetExecutionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get executions params
func (o *GetExecutionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get executions params
func (o *GetExecutionsParams) WithHTTPClient(client *http.Client) *GetExecutionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get executions params
func (o *GetExecutionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProjectID adds the projectID to the get executions params
func (o *GetExecutionsParams) WithProjectID(projectID string) *GetExecutionsParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the get executions params
func (o *GetExecutionsParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *GetExecutionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
