// Code generated by go-swagger; DO NOT EDIT.

package execution

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/testra/testra-cli/api/models"
)

// NewUpdateExecutionParams creates a new UpdateExecutionParams object
// with the default values initialized.
func NewUpdateExecutionParams() *UpdateExecutionParams {
	var ()
	return &UpdateExecutionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateExecutionParamsWithTimeout creates a new UpdateExecutionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateExecutionParamsWithTimeout(timeout time.Duration) *UpdateExecutionParams {
	var ()
	return &UpdateExecutionParams{

		timeout: timeout,
	}
}

// NewUpdateExecutionParamsWithContext creates a new UpdateExecutionParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateExecutionParamsWithContext(ctx context.Context) *UpdateExecutionParams {
	var ()
	return &UpdateExecutionParams{

		Context: ctx,
	}
}

// NewUpdateExecutionParamsWithHTTPClient creates a new UpdateExecutionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateExecutionParamsWithHTTPClient(client *http.Client) *UpdateExecutionParams {
	var ()
	return &UpdateExecutionParams{
		HTTPClient: client,
	}
}

/*UpdateExecutionParams contains all the parameters to send to the API endpoint
for the update execution operation typically these are written to a http.Request
*/
type UpdateExecutionParams struct {

	/*Body*/
	Body *models.ExecutionRequest
	/*ID
	  Execution Id

	*/
	ID string
	/*ProjectID
	  Project Id

	*/
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update execution params
func (o *UpdateExecutionParams) WithTimeout(timeout time.Duration) *UpdateExecutionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update execution params
func (o *UpdateExecutionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update execution params
func (o *UpdateExecutionParams) WithContext(ctx context.Context) *UpdateExecutionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update execution params
func (o *UpdateExecutionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update execution params
func (o *UpdateExecutionParams) WithHTTPClient(client *http.Client) *UpdateExecutionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update execution params
func (o *UpdateExecutionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update execution params
func (o *UpdateExecutionParams) WithBody(body *models.ExecutionRequest) *UpdateExecutionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update execution params
func (o *UpdateExecutionParams) SetBody(body *models.ExecutionRequest) {
	o.Body = body
}

// WithID adds the id to the update execution params
func (o *UpdateExecutionParams) WithID(id string) *UpdateExecutionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update execution params
func (o *UpdateExecutionParams) SetID(id string) {
	o.ID = id
}

// WithProjectID adds the projectID to the update execution params
func (o *UpdateExecutionParams) WithProjectID(projectID string) *UpdateExecutionParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the update execution params
func (o *UpdateExecutionParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateExecutionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
